name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: cypress/browsers:node16.5.0-chrome97-ff96
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      #   env:
      #     CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache/Cypress
      # - name: GitHub Action for Yarn
      #   uses: Borales/actions-yarn@v2.3.0
      # - name: Install dependencies
      #   run: yarn install
      # - name: Install Cypress
      #   uses: cypress-io/github-action@v2.9.7

      - name: "Update apt"
        run: sudo apt-get update
      - name: "Download Keybase"
        run: curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
      - name: "Install Keybase"
        run: sudo apt-get install ./keybase_amd64.deb unzip
      - name: "Run keybase globally"
        run: run_keybase -g
      - name: "Oneshot Keybase"
        run: keybase oneshot
        env:
          KEYBASE_USERNAME: ${{secrets.KEYBASE_USERNAME}}
          KEYBASE_PAPERKEY: ${{secrets.KEYBASE_PAPER_KEY}}
      - name: "Check file"
        run: ls
      - name: "Decrypt secrets"
        run: keybase decrypt -i _encrypted_internal -o _internal.zip
      - name: "Unzip"
        run: echo "A" | unzip _internal.zip -d _internal
      - name: "Check file"
        run: ls
      # - name: "Copy test wallet to root folder"
      #   run: mv _internal/test-wallet.json .
      - id: set_var
        name: "Read JSON file"
        run: |
          content=`cat _internal/test-wallet.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      # - name: "Show pk"
      #   run: |
      #     echo "${{fromJson(steps.set_var.outputs.packageJson).pk_automated_test_wallet}}"
      - name: "Run synpress"
        run: yarn synpress:run --browser chrome --config baseUrl=https://gallery.so screenshotOnRunFailure=false video=false
        env:
          PRIVATE_KEY: ${{fromJson(steps.set_var.outputs.packageJson).pk_automated_test_wallet}}
      # - run:
      #     name: "Install cli dependencies"
      #     command: sudo apt-get -y install unzip
      # - run:
      #     name: "Unzip secrets file"
      #     command: echo "A" | unzip _internal.zip -d _internal
      - name: "Add mask"
        run: |
          ls
          echo "::add-mask::filthyfansofpeanutbutter.com"
